%% 
addpath(genpath("/home/wairimu/leo-signal-proc/file_rw_utils"));
addpath(genpath("/home/wairimu/leo-signal-proc/matlab_utils"));
addpath(genpath("/home/wairimu/leo-signal-proc/ml"));
close all;
clear all;
%%
% downsampled by 3
Fs = 0.8e6;
load('/home/wairimu/haspatternsignals1.mat', 'haspatternsignals1');
disp("1");
% load('/home/wairimu/haspatternsignals2.mat', 'haspatternsignals2');
% disp("2");
load('/home/wairimu/nopatternsignals1.mat', 'nopatternsignals1');
disp("3");

% load('/home/wairimu/nopatternsignals2.mat', 'nopatternsignals2');
% disp("4");

%%

% signals = [haspatternsignals1 haspatternsignals2 nopatternsignals1 nopatternsignals2];

% labels = [repmat("has_pattern", 1, numel(haspatternsignals1)), ...
%           % repmat("has_pattern", 1, numel(haspatternsignals2)), ...
%           repmat("no_pattern", 1, numel(nopatternsignals1)), ...
%           % repmat("no_pattern", 1, numel(nopatternsignals2))];
% disp("5");

%%
haspatternsignals1 = abs(haspatternsignals1).^2;
nopatternsignals1 = abs(nopatternsignals1).^2;

haspatternsignals1 = haspatternsignals1(1:20, :);
signals = [haspatternsignals1; nopatternsignals1];
signals = transpose(signals);
% labels = [repmat("has_pattern", 1, numel(haspatternsignals1)), ...
%           repmat("no_pattern", 1, numel(nopatternsignals1))];


% Create class labels
classes = categorical(["has_pattern","no_pattern"]);
labels = repmat(classes,20,1);
labels = labels(:);

% return;

%% extract features
% 
% timeFE = signalTimeFeatureExtractor(SampleRate=100, ...
%     FrameSize=100, ...
%     FrameOverlapLength=30, ...
%     RMS=false, ...
%     CrestFactor=true, ...
%     ImpulseFactor=true, ...
%     StandardDeviation=true, ...
%     SNR=true, ...
%     ShapeFactor=true);
% 
timeFE = signalTimeFeatureExtractor(SampleRate=Fs, ...
    FrameSize=Fs, ...
    FrameOverlapLength=30, ...
    RMS=false, ...
    CrestFactor=true, ...
    ImpulseFactor=true, ...
    StandardDeviation=true, ...
    SNR=true, ...
    ShapeFactor=true);
disp("6");

[timeFeature,infoT] = extract(timeFE,signals);
% features = extract(timeFE,signals);
disp("7");
% disp(features);
%%


freqFE = signalFrequencyFeatureExtractor(SampleRate=Fs, ...
    FrameSize=Fs, ...
    FrameOverlapLength=30, ...
    MeanFrequency=true, ...
    BandPower=true, ...
    PeakLocation=true, ...
    PeakAmplitude=true, ...
    PowerBandwidth=true);
disp("8");

[freqFeature,infoF] = extract(freqFE,signals);
disp("9");
%%
% timeFreqFE = signalTimeFrequencyFeatureExtractor(SampleRate=Fs, ...
%     FrameSize=Fs, ...
%     FrameOverlapLength=30, ...
%     InstantaneousFrequency=true, ...
%     InstantaneousEnergy=false, ...
%     InstantaneousBandwidth=true, ...
%     TFRidges=true);
disp("10");

timeFreqFE = signalTimeFrequencyFeatureExtractor(SampleRate=Fs, ...
    FrameSize=Fs, ...
    FrameOverlapLength=30, ...
    SpectralKurtosis=true, ...
    SpectralFlatness=true, ...
    InstantaneousFrequency=true, ...
    InstantaneousEnergy=false, ...
    InstantaneousBandwidth=true, ...
    TFRidges=true, ...
    MeanEnvelopeEnergy=false);
[TimeFreqFeature,infoTF] = extract(timeFreqFE,signals);

%%
features = [timeFeature,freqFeature,TimeFreqFeature];
disp("11");

whos features

numChannel = size(features,2);
featureInfoTable = helperGetFeatureInfoTable({infoT,infoF,infoTF},numChannel);
featureInfoTable(1:10,:)

disp("12");
%%

splitIndices = splitlabels(labels,[0.7,0.1,0.2]);

featureTrain = features(:,:,splitIndices{1});
labelsTrain = labels(splitIndices{1});

featureVal = features(:,:,splitIndices{2});
labelsVal = labels(splitIndices{2});

featureTest = features(:,:,splitIndices{3});
labelsTest = labels(splitIndices{3});


numChannel = size(features,2);
offset = zeros(numChannel,1);
scaleFactor = ones(numChannel,1);
[featureTrainNorm,estMu,estSigmaSq] = batchnorm(dlarray(featureTrain), ...
    offset,scaleFactor, ...
    DataFormat="TCB");
featureValNorm = batchnorm(dlarray(featureVal), ...
    offset,scaleFactor, ...
    estMu,estSigmaSq, ...
    DataFormat="TCB");
featureTestNorm = batchnorm(dlarray(featureTest), ...
    offset,scaleFactor, ...
    estMu,estSigmaSq, ...
    DataFormat="TCB");
featureTrainNorm = extractdata(featureTrainNorm);
featureValNorm = extractdata(featureValNorm);
featureTestNorm = extractdata(featureTestNorm);

figure
clims = [0 8];
tiledlayout(3,4) 
for ii = 1:12
    nexttile
    imagesc(featureTrainNorm(:,:,ii))
    title(labels(ii))
end


dropoutProb = 0.2;
numFilters = 8;
numClasses = length(unique(labels));
inputSize = size(featureTrainNorm,[1 2])

layers = [ ...
    imageInputLayer(inputSize)
    convolution2dLayer([5,1],numFilters,Padding="same")
    batchNormalizationLayer
    reluLayer   
    dropoutLayer(dropoutProb)
    fullyConnectedLayer(numClasses)
    softmaxLayer];

options = trainingOptions("adam", ...
    Shuffle="every-epoch", ...
    Plots="training-progress", ...
    Metrics="accuracy", ...
    Verbose=false, ...
    MiniBatchSize=50, ...
    MaxEpochs=100, ...
    validationData={featureValNorm,labelsVal}, ...
    InputDataFormats="SSBC", ...
    ExecutionEnvironment="cpu");


net = trainnet(featureTrainNorm, ...
    labelsTrain, ...
    layers, ...
    "crossentropy", ...
    options);

classNames = categories(labelsTrain);
scores= minibatchpredict(net,featureTestNorm,InputDataFormats="SSBC");
labelsPred = scores2label(scores,classNames);

figure
confusionchart(labelsTest,labelsPred,Normalization="row-normalized")

